In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

archivo = "Nasa_Daily_merge_2020_2025.csv"
df = pd.read_csv(archivo)

print("Dimensión del dataset:", df.shape)
display(df.head())
display(df.dtypes)

Dimensión del dataset: (83134, 11)

C:\Users\USER\AppData\Local\Temp\ipykernel_16768\960393408.py:7: DtypeWarning: Columns (0: -BEGIN HEADER-, 1: Unnamed: 1, 2: Unnamed: 2, 3: Unnamed: 3, 4: Unnamed: 4, 5: Unnamed: 5, 6: Unnamed: 6, 7: Unnamed: 7, 8: Unnamed: 8, 9: Unnamed: 9, 10: Unnamed: 10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(archivo)

,-BEGIN HEADER-,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NASA/POWER Source Native Resolution Daily Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dates (month/day/year): 01/01/2020 through 12/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Location: Regional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,elevation from MERRA-2: Average for 0.5 x 0.62...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,The value for missing source data that cannot ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

-BEGIN HEADER-    object
Unnamed: 1        object
Unnamed: 2        object
Unnamed: 3        object
Unnamed: 4        object
Unnamed: 5        object
Unnamed: 6        object
Unnamed: 7        object
Unnamed: 8        object
Unnamed: 9        object
Unnamed: 10       object
dtype: object

In [2]:
raw = pd.read_csv(archivo, header=None, dtype=str)

fin_encabezado = raw.index[
    raw.iloc[:, 0].astype(str).str.strip().eq("-END HEADER-")
]

print("Filas donde termina el encabezado:", fin_encabezado.tolist())
display(raw.iloc[:20])

Filas donde termina el encabezado: [8]

,0,1,2,3,4,5,6,7,8,9,10
0,-BEGIN HEADER-,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
1,NASA/POWER Source Native Resolution Daily Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dates (month/day/year): 01/01/2020 through 12/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Location: Regional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,elevation from MERRA-2: Average for 0.5 x 0.62...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,The value for missing source data that cannot ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,parameter(s):,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,T2M MERRA-2 Temperature at 2 Meters (C),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,-END HEADER-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,LAT,LON,YEAR,MO,DY,T2M,PS,WS10M,WD10M,WS50M,WD50M
10,10.5,-75,2020,1,1,28.08,100.25,2.25,10.5,3.88,11.4
11,10.5,-74.375,2020,1,1,28.56,98.38,1.64,351.2,2.82,5.6
12,10.5,-73.75,2020,1,1,22.54,88.22,1.32,57.4,2.46,58.8
13,10.5,-73.125,2020,1,1,21.69,89.9,2,40.4,3.52,33.1
14,10.5,-72.5,2020,1,1,24.58,93.64,1.37,21.9,3.01,23.1
15,10.5,-71.875,2020,1,1,29.02,100.43,3.24,11.8,5.12,12.5
16,10.5,-71.25,2020,1,1,30.06,99.77,3.67,30.9,5.28,35.7
17,11,-75,2020,1,1,27.89,100.57,6.9,39,8.66,39
18,11,-74.375,2020,1,1,27.5,98.21,4.97,44,6.24,46.1
19,11,-73.75,2020,1,1,21.67,88.81,3.23,77.2,4.31,81.6

In [3]:
df = pd.read_csv(archivo, skiprows=9)

df["FECHA"] = pd.to_datetime(
    dict(year=df["YEAR"], month=df["MO"], day=df["DY"])
)

print("Dimensión limpia:", df.shape)
display(df.head())
display(df.dtypes)

Dimensión limpia: (83125, 12)

,LAT,LON,YEAR,MO,DY,T2M,PS,WS10M,WD10M,WS50M,WD50M,FECHA
0,10.5,-75.000,2020,1,1,28.08,100.25,2.25,10.5,3.88,11.4,2020-01-01
1,10.5,-74.375,2020,1,1,28.56,98.38,1.64,351.2,2.82,5.6,2020-01-01
2,10.5,-73.750,2020,1,1,22.54,88.22,1.32,57.4,2.46,58.8,2020-01-01
3,10.5,-73.125,2020,1,1,21.69,89.90,2.00,40.4,3.52,33.1,2020-01-01
4,10.5,-72.500,2020,1,1,24.58,93.64,1.37,21.9,3.01,23.1,2020-01-01

LAT             float64
LON             float64
YEAR              int64
MO                int64
DY                int64
T2M             float64
PS              float64
WS10M           float64
WD10M           float64
WS50M           float64
WD50M           float64
FECHA    datetime64[us]
dtype: object